namespace PCBStore.Data.Models.Enums
{
   public enum ManufacturersEnum
   {

      AMISemiconductor = 1,
      AdvancedSemiconductor =2,
      AnalogDevices = 3,
      Atmel=4,
      AvagoTechnologies=5,
      CosmicCircuits=6,
      CrocusTechnology=7,
      DynexSemiconductor=8,
      ElpidaMemory=9,
      FairchildSemiconductor=10,
      FreescaleSemiconductor=11,
      Fujitsu = 11,
      Hynix=12,
      IBM=13,
      IMFlashTechnologies=14,
      InfineonTechnologies=15,
      Inotera=16,
      IntelCorporation=17,
      InternationalRectifier=18,
      IPtronics=19,
      JennicLimited=20,
      Luxtera=21,
      MaterialsResearchCorporation=22,
      MaximIntegratedProducts=23,
      MicrochipTechnology=24,
      MicronTechnology=25,
      NationalSemiconductor=26,
      NEC=27,
      NemotekTechnologie=28,
      Numonyx=29,
      Nuvoton=30,
      NXPSemiconductors=31,
      ONSemiconductor=32,
      Oramir=33,
      PanasonicCorporation=34,
      Qimonda=35,
      ReadingWorks=36,
      RenesasTechnology=37,
      SamsungElectronics=38,
      Sanyo=40,
      Seiko=41,
      SensorDynamics=42,
      SharpCorporation=43,
      Sitronics=44,
      Sony=45,
      STMicroelectronics=46,
      TexasInstruments=47,
      Toshiba=48,
      TriQuintSemiconductor=49,
      Winbond=50,
   

      Others = 1000
   }
}
